// // <auto-generated />
// using System;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using todo_planner.DataL.Data;

// #nullable disable

// namespace todo_planner.Migrations
// {
//     [DbContext(typeof(AppDbContext))]
//     [Migration("20251026191430_ChangePassToHash")]
//     partial class ChangePassToHash
//     {
//         /// <inheritdoc />
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

//             modelBuilder.Entity("todo_planner.Models.Task", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Description")
//                         .IsRequired()
//                         .HasMaxLength(500)
//                         .HasColumnType("TEXT");

//                     b.Property<DateTime>("DueDate")
//                         .HasColumnType("TEXT");

//                     b.Property<int>("Priority")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Status")
//                         .HasColumnType("INTEGER");

//                     b.Property<string>("Title")
//                         .IsRequired()
//                         .HasMaxLength(100)
//                         .HasColumnType("TEXT");

//                     b.Property<DateTime?>("UpdatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("Id");

//                     b.HasIndex("UserId");

//                     b.ToTable("Tasks");

//                     b.HasData(
//                         new
//                         {
//                             Id = 1,
//                             CreatedAt = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Finish the semester project documentation",
//                             DueDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
//                             Priority = 3,
//                             Status = 2,
//                             Title = "Complete project proposal",
//                             UserId = 1
//                         },
//                         new
//                         {
//                             Id = 2,
//                             CreatedAt = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Milk, eggs, bread, and fruits",
//                             DueDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
//                             Priority = 1,
//                             Status = 1,
//                             Title = "Buy groceries",
//                             UserId = 1
//                         },
//                         new
//                         {
//                             Id = 3,
//                             CreatedAt = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Prepare for advanced programming test",
//                             DueDate = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Local),
//                             Priority = 2,
//                             Status = 1,
//                             Title = "Study for exams",
//                             UserId = 2
//                         });
//                 });

//             modelBuilder.Entity("todo_planner.Models.User", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Email")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("TEXT");

//                     b.Property<string>("PasswordHash")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<DateTime?>("UpdatedAt")
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.ToTable("Users");

//                     b.HasData(
//                         new
//                         {
//                             Id = 1,
//                             CreatedAt = new DateTime(2024, 1, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
//                             Email = "john@example.com",
//                             Name = "John Doe",
//                             PasswordHash = "password123"
//                         },
//                         new
//                         {
//                             Id = 2,
//                             CreatedAt = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
//                             Email = "jane@example.com",
//                             Name = "Jane Smith",
//                             PasswordHash = "password123"
//                         });
//                 });

//             modelBuilder.Entity("todo_planner.Models.Task", b =>
//                 {
//                     b.HasOne("todo_planner.Models.User", "User")
//                         .WithMany("Tasks")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("User");
//                 });

//             modelBuilder.Entity("todo_planner.Models.User", b =>
//                 {
//                     b.Navigation("Tasks");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo_planner.DataL.Data;

#nullable disable

namespace todo_planner.Migrations
{
    [DbContext(typeof(AppDbContext))] // Specifies the context this migration is associated with
    [Migration("20251026191430_ChangePassToHash")] // Unique identifier for the migration
    partial class ChangePassToHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) // Builds the target model for the database
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10"); // Sets the product version for EF Core

            // Define the 'Task' entity
            modelBuilder.Entity("todo_planner.Models.Task", b =>
            {
                // Primary key definition
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd() // Automatically create a value for the ID when added
                    .HasColumnType("INTEGER");

                // Other properties with their types and constraints
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired() // Field cannot be null
                    .HasMaxLength(500) // Maximum length of 500 characters
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DueDate")
                    .HasColumnType("TEXT");

                b.Property<int>("Priority")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired() // Field cannot be null
                    .HasMaxLength(100) // Maximum length of 100 characters
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt") // Nullable field for last updated timestamp
                    .HasColumnType("TEXT");

                b.Property<int>("UserId") // Foreign key reference to the User entity
                    .HasColumnType("INTEGER");

                // Set primary key and index
                b.HasKey("Id"); // Define primary key
                b.HasIndex("UserId"); // Create an index on UserId for performance

                b.ToTable("Tasks"); // Map to the 'Tasks' table

                // Seed initial data for the 'Tasks' table
                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedAt = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Finish the semester project documentation",
                        DueDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
                        Priority = 3, // Priority level
                        Status = 2, // Status level
                        Title = "Complete project proposal",
                        UserId = 1 // Associated user
                    },
                    new
                    {
                        Id = 2,
                        CreatedAt = new DateTime(2024, 1, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Milk, eggs, bread, and fruits",
                        DueDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                        Priority = 1,
                        Status = 1,
                        Title = "Buy groceries",
                        UserId = 1
                    },
                    new
                    {
                        Id = 3,
                        CreatedAt = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Prepare for advanced programming test",
                        DueDate = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Local),
                        Priority = 2,
                        Status = 1,
                        Title = "Study for exams",
                        UserId = 2
                    });
            });

            // Define the 'User' entity
            modelBuilder.Entity("todo_planner.Models.User", b =>
            {
                // Primary key definition
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd() // Automatically create a value for the ID when added
                    .HasColumnType("INTEGER");

                // Define other properties with types and constraints
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired() // Field cannot be null
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired() // Field cannot be null
                    .HasMaxLength(50) // Maximum length of 50 characters
                    .HasColumnType("TEXT");

                b.Property<string>("PasswordHash") // Changed to store hashed passwords for security
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt") // Nullable field for last updated timestamp
                    .HasColumnType("TEXT");

                // Set primary key
                b.HasKey("Id");
                b.ToTable("Users"); // Map to the 'Users' table

                // Seed initial data for the 'Users' table
                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedAt = new DateTime(2024, 1, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        Email = "john@example.com",
                        Name = "John Doe",
                        PasswordHash = "password123" // Placeholder; should be replaced with an actual hashed value
                    },
                    new
                    {
                        Id = 2,
                        CreatedAt = new DateTime(2024, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        Email = "jane@example.com",
                        Name = "Jane Smith",
                        PasswordHash = "password123" // Placeholder; should be replaced with an actual hashed value
                    });
            });

            // Set up relationships between entities
            modelBuilder.Entity("todo_planner.Models.Task", b =>
            {
                // Define relationship with User
                b.HasOne("todo_planner.Models.User", "User") // Each Task belongs to a User
                    .WithMany("Tasks") // A User can have multiple Tasks
                    .HasForeignKey("UserId") // Foreign key property
                    .OnDelete(DeleteBehavior.Cascade) // If User is deleted, related Tasks will also be deleted
                    .IsRequired();

                b.Navigation("User"); // Navigation property for User
            });

            modelBuilder.Entity("todo_planner.Models.User", b =>
            {
                b.Navigation("Tasks"); // Navigation property for Tasks
            });
#pragma warning restore 612, 618
        }
    }
}

/*
 * Purpose of this file:
 * 
 * This migration file defines modifications to the existing database schema in the todo_planner application.
 * Specifically, it updates the 'Users' table to store hashed passwords instead of plaintext passwords, enhancing security.
 * 
 * The Tasks and Users tables are defined, with their properties, relationships, and constraints.
 * 
 * Additionally, this file seeds the database with initial data for both Tasks and Users, creating a starting point 
 * for the application's task management functionality.
 * 
 * The relationships established ensure referential integrity, meaning that if a User is deleted, all associated 
 * Tasks will also be removed, helping maintain a consistent state in the database.
 */
