// // <auto-generated />
// using System;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using todo_planner.DataL.Data;

// #nullable disable

// namespace todo_planner.Migrations
// {
//     [DbContext(typeof(AppDbContext))]
//     partial class AppDbContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

//             modelBuilder.Entity("todo_planner.Models.Task", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Description")
//                         .IsRequired()
//                         .HasMaxLength(500)
//                         .HasColumnType("TEXT");

//                     b.Property<DateTime>("DueDate")
//                         .HasColumnType("TEXT");

//                     b.Property<int>("Priority")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Status")
//                         .HasColumnType("INTEGER");

//                     b.Property<string>("Title")
//                         .IsRequired()
//                         .HasMaxLength(100)
//                         .HasColumnType("TEXT");

//                     b.Property<DateTime?>("UpdatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("Id");

//                     b.HasIndex("UserId");

//                     b.ToTable("Tasks");
//                 });

//             modelBuilder.Entity("todo_planner.Models.User", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<DateTime>("CreatedAt")
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Email")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("TEXT");

//                     b.Property<string>("PasswordHash")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<DateTime?>("UpdatedAt")
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.ToTable("Users");
//                 });

//             modelBuilder.Entity("todo_planner.Models.Task", b =>
//                 {
//                     b.HasOne("todo_planner.Models.User", "User")
//                         .WithMany("Tasks")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("User");
//                 });

//             modelBuilder.Entity("todo_planner.Models.User", b =>
//                 {
//                     b.Navigation("Tasks");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }


using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo_planner.DataL.Data;

#nullable disable

namespace todo_planner.Migrations
{
    [DbContext(typeof(AppDbContext))] // Specifies the context this snapshot is associated with
    partial class AppDbContextModelSnapshot : ModelSnapshot // Represents the current model snapshot for the DB context
    {
        protected override void BuildModel(ModelBuilder modelBuilder) // Builds the database model including configuration details
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10"); // Sets the product version for EF Core

            // Define the 'Task' entity
            modelBuilder.Entity("todo_planner.Models.Task", b =>
            {
                b.Property<int>("Id") // Primary key for the Task entity
                    .ValueGeneratedOnAdd() // Automatically generate a value on insert
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt") // Timestamp when the task was created
                    .HasColumnType("TEXT");

                b.Property<string>("Description") // Task description
                    .IsRequired() // Field cannot be null
                    .HasMaxLength(500) // Maximum length of 500 characters
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DueDate") // Due date for the task
                    .HasColumnType("TEXT");

                b.Property<int>("Priority") // Priority level of the task
                    .HasColumnType("INTEGER");

                b.Property<int>("Status") // Current status of the task
                    .HasColumnType("INTEGER");

                b.Property<string>("Title") // Title of the task
                    .IsRequired() // Field cannot be null
                    .HasMaxLength(100) // Maximum length of 100 characters
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt") // Nullable timestamp for last update
                    .HasColumnType("TEXT");

                b.Property<int>("UserId") // Foreign key referencing the User entity
                    .HasColumnType("INTEGER");

                b.HasKey("Id"); // Set the primary key

                b.HasIndex("UserId"); // Create an index on UserId for performance

                b.ToTable("Tasks"); // Map to the 'Tasks' table
            });

            // Define the 'User' entity
            modelBuilder.Entity("todo_planner.Models.User", b =>
            {
                b.Property<int>("Id") // Primary key for the User entity
                    .ValueGeneratedOnAdd() // Automatically generate a value on insert
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt") // Timestamp when the user was created
                    .HasColumnType("TEXT");

                b.Property<string>("Email") // User's email address
                    .IsRequired() // Field cannot be null
                    .HasColumnType("TEXT");

                b.Property<string>("Name") // User's name
                    .IsRequired() // Field cannot be null
                    .HasMaxLength(50) // Maximum length of 50 characters
                    .HasColumnType("TEXT");

                b.Property<string>("PasswordHash") // Store hashed passwords for security
                    .IsRequired() 
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt") // Nullable timestamp for last user update
                    .HasColumnType("TEXT");

                b.HasKey("Id"); // Set the primary key
                b.ToTable("Users"); // Map to the 'Users' table
            });

            // Set up relationships between entities
            modelBuilder.Entity("todo_planner.Models.Task", b =>
            {
                b.HasOne("todo_planner.Models.User", "User") // Each Task belongs to one User
                    .WithMany("Tasks") // A User can have many Tasks
                    .HasForeignKey("UserId") // Foreign key on Task
                    .OnDelete(DeleteBehavior.Cascade) // If a User is deleted, related Tasks will also be deleted
                    .IsRequired();

                b.Navigation("User"); // Navigation property to User
            });

            modelBuilder.Entity("todo_planner.Models.User", b =>
            {
                b.Navigation("Tasks"); // Navigation property to Tasks
            });
#pragma warning restore 612, 618
        }
    }
}

/*
 * Purpose of this file:
 * 
 * This file represents the current state of the model snapshot for the AppDbContext within the todo_planner application.
 * It defines the structure and configuration of the 'Tasks' and 'Users' tables, including their properties, constraints, 
 * and relationships.
 * 
 * The Tasks table tracks various task attributes, such as title, description, due date, priority level, and status, 
 * while associating each task with a user through a foreign key. 
 * 
 * The Users table stores user details like name, email, and password hash, ensuring that sensitive information is stored securely.
 * 
 * This snapshot is crucial for Entity Framework migrations, enabling the tracking of changes to the model over time and assisting 
 * in updating the database schema accordingly.
 */
